### ISSUE TITLE
Improved documentation 

### ISSUE THREAD

**Issue by mohammedhammaad18** [DMU-CTEC2902-2022/BrainStormers_Team#7]
For the class diagram, we have changed the ModuleName into ModuleTitle and ModuleContent to ModuleCode for the attributes. We as the system analyst/coordinators did this as we didn't read the assignment brief properly.

**Comment by IbrahimZahid1** [comment]
some suggestions were made by the developers side for the class diagram alterations and system analysts acknowledged and resolved the issue accordingly
